version: '3.8'
services:
  db:
    image: mariadb:10.5
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: hotcrp
      MYSQL_USER: hotcrp
      MYSQL_PASSWORD: hotcrp
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3307:3306"
    command: --max-allowed-packet=32M

  web:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    depends_on:
      - db
    volumes:
      - ..:/var/www/html
      - ./php.ini:/usr/local/etc/php/php.ini
    ports:
      - "8080:80"
    environment:
      - APACHE_DOCUMENT_ROOT=/var/www/html

  mailhog:
    image: mailhog/mailhog
    ports:
      - "8025:8025"
      - "1026:1025"

volumes:
  db_data:
